### ISSUE TITLE
Elodie stops running after jumping in the base of a wall.

### ISSUE THREAD

**Issue by BinaryBrain** [BinaryBrain/Elodie-Dream#14]
Elodie stops running after landing a jump **exactly** at the base of a wall.
I think both `right` and `bottom` collisions happends at once and this cause the character to stop.

I didn't investigate to know if this come from the Collision system or the `Elodie::doStuff` methode.

**Comment by Gerardufoin** [comment]
I corrected the bug partially, it comes from the Collision system. I don't find the algo really great, there is some light problems because it apparently doesn't check everything it should.

The algo for the movements will not be the same in the real game, as the speed will not be reduce to 0 in case of collisions in both side (as she won't bounce on the walls) so it should work anyway. But I'd like to find out what causes this bug when we'll have more time.

I'll continue to search a fix this evening. But if I don't find one right away, I'll probably try to work on something else in the meantime.

**Comment by Gerardufoin** [comment]
The bug was not a collisions problem, but the way we changed the speed in fonction of the collisions. Fixed.
