### ISSUE TITLE
Auto-save

### ISSUE THREAD

**Issue by BinaryBrain** [BinaryBrain/Elodie-Dream#24]
I think auto-saving the game could be a great feature.
First of all, if you load a game, everytime you finish a level, it should be automatically saved.
If you just create a new game, the game should auto-save in the first open slot if there are not all full.

**Comment by Protectator** [comment]
What part is there still to do here ?

**Comment by BinaryBrain** [comment]
I don't know if it's working properly. If so, @Flagoul should close it.

**Comment by BasileVu** [comment]
At the moment, the progress is automatically saved after a level (pick the more recent event):
- On the last slot which from you loaded a game
- On the last slot you saved

When starting a new game, the autosave is currently disabled, so there is still the save on an empty slot to implement. I didn't do it yet because I felt it would be unclear which save is the latest.

So I thought it could be great if we could do something like highlighting the slot with the most recent save for example.

**Comment by BinaryBrain** [comment]
What about calling the `save` method when clicking `new game` in the menu? And we save it on the first empty slot found. If there is no empty slot left, we just don't save.

**Comment by BasileVu** [comment]
Yeah, we could do that. At the same time, I'll try to add something to see which save is the more recent (the date of the save for example).
