### ISSUE TITLE
Scoring System

### ISSUE THREAD

**Issue by Protectator** [BinaryBrain/Elodie-Dream#39]
We should improve a bit the scoring system by putting adding more granularity to bonus points by defning some (new) clear bonus and points system. Discuss your ideas (both in form and substance) here !

**Comment by jrabasco** [comment]
I have some ideas : 
- Number of jumps, the less jumps you do, the higher your score. You can implement it in two ways :  
  1. for each map you try to count some ideal number of jumps (either a minimum or something close to it), call it I, and count the number of jumps the player did, call it A. Then the score gained from this would be MAX(0, MAX_SCORE - (I-A)*JUMP_VALUE) (so that it is not negative).
  2. Set is as a multiplier (that multiplies the total score) and for each jump decrease the multiplier. Let N be the number of jumps the player did. Then the multiplier would be of the form 1 + 1/f(N) where f is a function that is 1 when N is 0 (so the max multiplier would be 2) and is increasing in a way that you can still get a good score in levels when you are forced to jump a lot.
- Add new items, specifically ones that grant a lot of point if you chose a hard path.
- Combos : the more enemies you kill without getting hit the more points you get for each kill

**Comment by BasileVu** [comment]
What we have actually (see private members): https://github.com/BinaryBrain/Elodie-Dream/blob/master/src/Score/Score.h

**Comment by jrabasco** [comment]
Is it hard to count jumps, add items, or keep track of more stuff in the current system ?

**Comment by BasileVu** [comment]
Actually it's pretty simple:
- For the jumps, since there is an event which triggers if the jump key is pressed, we can just put a counter there.
- To add items, we should juste create new Entities, like the Bonus (https://github.com/BinaryBrain/Elodie-Dream/blob/master/src/Entity/Bonus.h).
- I think implementing more stuff such as more points for more kills whithout damages taken could be simple as well (for example a kill counter which resets when hit).
